sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.2.3
  - 2.3.0
  - 2.4.0
  - jruby-9.1.7.0
notifications:
  irc:
    - "irc.freenode.net#sensu"
addons:
  code_climate:
    repo_token: 824f4a75343a9300704f23e93eaaecb25d998e408f2c9b96cd44f55983d95483
